version: "3.1"

services:
  api:
    build: .
    networks:
      - bd
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:11
    networks:
      - bd
    ports:
      - 5432:5432
    volumes:
      - desafio_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
  client:
    image: dpage/pgadmin4
    networks:
      - bd
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ol.com
      PGADMIN_DEFAULT_PASSWORD: senha#123

networks:
  bd: { }
volumes:
  desafio_db_volume: {}