version: "3.1"

services:
  db:
    image: postgres:11
    networks:
      - bd
    volumes:
      - desafio_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: desafio
    ports:
      - 5432:5432
  api:
    image: rafaelcmedrado/desafio:latest
    networks:
      - bd
    environment:
      API_PORT: 80
      API_LOG_LEVEL: INFO
      DB_PROTOCOL: postgres
      DB_USERNAME: postgres
      DB_SECRET: example
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: desafio
      DB_OPTIONS: sslmode=disable
    ports:
      - 80:80
    depends_on:
      - db
networks:
  bd: { }
volumes:
  desafio_db_volume: { }